export const actiontypes = {
  SET_PRODUCTS: "SET-PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  SET_MENS_CLOTHING: "SET_MENS_CLOTHING",
  SET_USER: "SET_USER",
  SET_ADD_TO_CART: "SET_ADD_TO_CART",
  SET_CART_REMOVE: "SET_CART_REMOVE",
  SET_PLUS_QTY: "SET_PLUS_QTY",
  SET_MINUS_QTY: "SET_MINUS_QTY",
  FETCH_PRODUCTS:"FETCH_PRODUCTS"
};
